#!/bin/bash
# DO NOT EDIT THIS FILE
# This file is controlled by Drainpipe, run composer install to apply pending
# updates.

set -eux
echo "Building..."

./vendor/bin/task build
if [ -d "${TUGBOAT_ROOT}/web/modules/contrib/memcache" ]; then
  ./vendor/bin/task update
else
  echo "⚠️ Memcache no está disponible, se omite 'task update' para evitar fallos"
fi

