#!/bin/bash
# DO NOT EDIT THIS FILE
# This file is controlled by Drainpipe, run composer install to apply pending
# updates.

set -eux
echo "Building..."

# Instala usando perfil minimal
drush site:install minimal --account-name=admin --account-pass=admin -y

# Aplica el UUID exportado
uuid=$(grep uuid conf/drupal/config/system.site.yml | awk '{print $2}')
drush cset system.site uuid "$uuid" -y

# Exporta para forzar que tome el nuevo UUID como válido
drush config:export -y

# Elimina entidades conflictivas (si existen)
drush entity:delete shortcut_set || true
drush entity:delete shortcut || true

# Ejecuta el build y update
./vendor/bin/task build
./vendor/bin/task update
